/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/three/daniel-whole.gltf -t -m --shadows -d -T -S
Files: public/three/daniel-whole.gltf [2.76KB] > /var/www/html/daniel-whole-transformed.glb [20.38KB] (-638%)
*/
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import { GLTFAction } from "@/types/global";

type GLTFResult = {
  animations: GLTFAction[];
  materials: {
    ["Outer.009"]: THREE.MeshStandardMaterial;
  };
  nodes: {
    Daniel_Whole: THREE.Mesh;
  };
} & GLTF;

const PATH = "/three/daniel-whole-transformed.glb";

export function DanielWholeTransformed(props: JSX.IntrinsicElements["group"]) {
  const { materials, nodes } = useGLTF(PATH) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.Daniel_Whole.geometry}
        material={materials["Outer.009"]}
        material-wireframe={true}
        receiveShadow
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
        userData={{ name: "Daniel_Whole" }}
      />
    </group>
  );
}

useGLTF.preload(PATH);
