/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/3D/daniel-fractured.gltf -t -m --shadows -d
*/

import { GLTFAction } from "@/types";
import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = {
  animations: GLTFAction[];
  materials: {
    ["Inner.004"]: THREE.MeshStandardMaterial;
    ["Outer.008"]: THREE.MeshStandardMaterial;
  };
  nodes: {
    Untitled053: THREE.Mesh;
    Untitled053_1: THREE.Mesh;
    Untitled054: THREE.Mesh;
    Untitled054_1: THREE.Mesh;
    Untitled055: THREE.Mesh;
    Untitled055_1: THREE.Mesh;
    Untitled056: THREE.Mesh;
    Untitled056_1: THREE.Mesh;
    Untitled057: THREE.Mesh;
    Untitled057_1: THREE.Mesh;
    Untitled058: THREE.Mesh;
    Untitled058_1: THREE.Mesh;
    Untitled059: THREE.Mesh;
    Untitled059_1: THREE.Mesh;
    Untitled060: THREE.Mesh;
    Untitled060_1: THREE.Mesh;
    Untitled061: THREE.Mesh;
    Untitled061_1: THREE.Mesh;
    Untitled062: THREE.Mesh;
    Untitled062_1: THREE.Mesh;
    Untitled063: THREE.Mesh;
    Untitled063_1: THREE.Mesh;
    Untitled064: THREE.Mesh;
    Untitled064_1: THREE.Mesh;
    Untitled065: THREE.Mesh;
    Untitled065_1: THREE.Mesh;
    Untitled066: THREE.Mesh;
    Untitled066_1: THREE.Mesh;
  };
} & GLTF;

const PATH = "/3D/daniel-fractured.gltf";

export function DanielFractured(props: JSX.IntrinsicElements["group"]) {
  const { materials, nodes } = useGLTF(PATH) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
        userData={{ name: "Daniel_Fractured" }}
      >
        <group
          position={[-3.531, 16.236, 2.264]}
          userData={{ name: "Daniel_01" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled059.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled059_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-5.886, 8.587, -16.678]}
          userData={{ name: "Daniel_02" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled053.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled053_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-4.181, -2.056, 1.598]}
          userData={{ name: "Daniel_03" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled058.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled058_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[4.792, 1.904, -8.297]}
          userData={{ name: "Daniel_04" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled054.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled054_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[12.041, 12.186, -11.755]}
          userData={{ name: "Daniel_05" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled064.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled064_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-5.641, 2.589, -17.962]}
          userData={{ name: "Daniel_06" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled056.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled056_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[0.886, -21.342, 21.969]}
          userData={{ name: "Daniel_07" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled065.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled065_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-0.097, 5.021, 9.519]}
          userData={{ name: "Daniel_08" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled063.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled063_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-1.318, 17.967, -1.765]}
          userData={{ name: "Daniel_09" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled055.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled055_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-11.934, 20.144, -12.099]}
          userData={{ name: "Daniel_10" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled061.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled061_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[2.049, 1.464, -15.063]}
          userData={{ name: "Daniel_11" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled066.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled066_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[5.493, 4.32, -20.565]}
          userData={{ name: "Daniel_12" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled060.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled060_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[0.526, -18.012, 4.453]}
          userData={{ name: "Daniel_13" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled057.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled057_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
        <group
          position={[-0.298, 20.199, -12.582]}
          userData={{ name: "Daniel_14" }}
        >
          <mesh
            castShadow
            geometry={nodes.Untitled062.geometry}
            material={materials["Outer.008"]}
            receiveShadow
          />
          <mesh
            castShadow
            geometry={nodes.Untitled062_1.geometry}
            material={materials["Inner.004"]}
            receiveShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(PATH);
