/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/3D/daniel-whole.gltf
*/

import { DanielGLTF } from "@/types";
import { useGLTF } from "@react-three/drei";
import React from "react";

const PATH = "/3D/daniel-whole.gltf";
type Props = JSX.IntrinsicElements["group"];

export function Daniel(props: Props) {
  const { materials, nodes } = useGLTF(PATH) as DanielGLTF;
  console.log(nodes);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Daniel_Whole.geometry}
        material={materials["Outer.009"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload(PATH);
