import type { Metadata } from "next";

import "@/styles/globals.css";
import cx from "classnames";
import { Fira_Code } from "next/font/google";

const firaCode = Fira_Code({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const className = cx(firaCode.variable);
  return (
    <html lang="en">
      <body className={`${className} antialiased`}>{children}</body>
    </html>
  );
}
